# site settings
title: Open Sourced Blogging
email: mahinthjoe@gmail.com
description: "Novelty of manner may compensate for triteness of subject. David Hume"
baseurl: ""
url: "http://mahinthjoe.github.io"
twitter_username: mahinthjoe
github_username:  mahinthjoe
include: ['.htaccess']
keep_files: ['.git']
extensions: ['fenced_code_blocks']
# Build settings
markdown: kramdown
permalink: pretty
