# Site settings
title: Learning Modular Branching
email: joe@mjacesolutions.com
description: "Ticket based  support via http://mjac.freshdesk.com Attempting to cosolidate all the different notes I have obtained over the years. In a location independant way with hosting provided by github.com come on lets learn something while you are here. Unfortunately organization with filters, tags and collection requires the use of third party plugins. 
baseurl: ""
url: "http://mahinthjoe.github.io"
twitter_username: mahinthjoe
github_username:  mahinthjoe
include: ['.htaccess']
keep_files: ['.git']
extensions: ['fenced_code_blocks']
# Build settings
markdown: kramdown
permalink: pretty
